version: '3.3'

services:

  db:
    container_name: coingraph_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: coingraph
    volumes:
      - coingraph_postgress_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  coingraph_postgress_volume: 

networks:
  coingraph_network:
